#!/usr/bin/env bash
# This is a Bash script that displays lines containing the bash word,
# shellcheck disable=SC2009
# thus allowing you to easily get the PID of your Bash process.
# Requirements:
#	You cannot use pgrep
#	The third line of your script must be # shellcheck disable=SC2009

ps -faux | grep bash
