#!/usr/bin/env bash
# This is a Bash script that displays the content of the file /etc/passwd.
# The script only displays:
# username
# user id
# Home directory path for the user

while IFS=: read -r username _ userid _ _ _ home _
do
    echo "Username: $username, User ID: $userid, Home Directory: $home"
done < /etc/passwd
