#!/usr/bin/env bash
# This is a Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
# Requirement:
#	Format: OCCURENCE_NUMBER IP HTTP_CODE
#		in a list format
#	Ordered from the greatest to the lowest number of occurrences
#		See example
#	You must use awk
#	You are not allowed to use while, for, until and cut

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
